version: '3'

services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile-Spring
    container_name: paperless-spring
    ports:
      - "8081:8081"
    expose:
      - "8081"
  nginx:
    build:
      context: ./paperless-ngx-ui
      dockerfile: Dockerfile-UI
    container_name: paperless-ui
    ports:
      - "80:80"
    expose:
      - "80"
