version: '3'

services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile-Spring
    container_name: paperless-spring
    ports:
      - "8081:8081"
    expose:
      - "8081"
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    build:
      context: ./paperless-ngx-ui
      dockerfile: Dockerfile-UI
    container_name: paperless-ui
    ports:
      - "80:80"
    expose:
      - "80"
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=paperless
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 15s
      timeout: 5s
      retries: 5
